sudo: false
dist: trusty
language: minimal

before_install:
  - "wget 'https://raw.githubusercontent.com/mpeterv/hererocks/0.16.0/hererocks.py' \
        && echo '6ae35e5cd6d34775f8190f51331d850b34ce0fac  hererocks.py' | sha1sum -c || exit 1"
  - python hererocks.py .venv --lua=5.2 --luarocks=^
  - source .venv/bin/activate
install:
  - luarocks install luacheck
script:
  - make lint

notifications:
  irc:
    channels:
      - "chat.freenode.net#alpine-commits"
    template:
      - "%{repository_name}:%{branch} |{author}| %{commit_subject} >> %{result} | %{build_url}"
